apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-web-test
spec:
  replicas: 1
  selector:
    role: web-frontend
  template:
    metadata:
      labels:
        role: web-frontend
    spec:
      containers:
      - name: web
        image: nginx
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
            - name: nfs
              mountPath: "/usr/share/nginx/html"
              readOnly: true
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
