apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: jenkins
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: gcr.io/cloudsql-docker/gce-proxy:1.11
        name: mysql
        command: ["/cloud_sql_proxy",
                    "-instances=insly-testing:us-central1:test-ci=tcp:0.0.0.0:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
        ports:
        - containerPort: 3306
          name: mysql

      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
