apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: jenkins
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nfs-server.nfs.svc.cluster.local
    path: "/"
