apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
  namespace: nfs
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/pv-1
